name: kind

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run build

      - name: Create cluster
        uses: ./
        id: kind

      - name: Output
        run: echo "${{ steps.kind.outputs.kubeConfigPath }}"
