name: "Tests"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run build
      - uses: ./
        with:
          waitDuration: 60s
          configFile: .github/kind-config.yaml
