name: chart actions

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build kind action
        working-directory: ./kind
        run: |
          npm install
          npm run build

      - name: Build chart-testing action
        working-directory: ./chart-testing
        run: |
          npm install
          npm run build

      - name: Build chart-releaser action
        working-directory: ./chart-releaser
        run: |
          npm install
          npm run build

      - name: Create cluster
        uses: ./kind
        with:
          installLocalPathProvisioner: true

      - name: Run chart-testing
        uses: ./chart-testing
        with:
          command: version

      - name: Run chart-releaser
        uses: ./chart-releaser
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
