name: chart actions

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create cluster
        uses: unguiculus/kind-action@remove-typescript
        with:
          installLocalPathProvisioner: true

      - name: Run chart-testing (lint)
        uses: unguiculus/chart-testing-action@master
        with:
          command: lint

      - name: Run chart-testing (install)
        uses: unguiculus/chart-testing-action@master
        with:
          command: install

      - name: Run chart-releaser
        uses: unguiculus/chart-releaser-action@remove-typescript
        with:
          owner: unguiculus
          repo: actions-test
          token: "${{ secrets.GITHUB_TOKEN }}"
