name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release
        run: |
          echo "Releasing version: ${{ github.event.inputs.version }}"
