name: chart actions

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email unguiculus@users.noreply.github.com

      - name: Run chart-releaser
        uses: scottrigby/chart-releaser-action@master
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
